### ISSUE TITLE
Internal server error in /bound/

### ISSUE THREAD

**Issue by aptiko** [openmeteo/enhydris#15]
http://main.hydroscope.gr/bound/?political_division=0

DoesNotExist: PoliticalDivision matching query does not exist.

**Comment by kickapoo** [comment]
In development mode `/bound/?political_division=0` returns `Page not found` .  Am I missing something? can you provide some details

**Comment by aptiko** [comment]
The `/bound` url was changed to `/bounding_box` in 1dab0b76b63. `/bounding_box/?political_division=0` does not cause an error any more. It is likely that this bug was fixed in that same commit (or anyway in the large overhaul that was merged in 7874682).
