### ISSUE TITLE
Clean up the code for the list of stations

### ISSUE THREAD

**Issue by aptiko** [openmeteo/enhydris#156]
The code for the list of stations is currently in a page. Is that OK, or should the list become a component? Should it be unit-tested?

I don't really have an opinion on how it should be. It currently seems to me it should become a component, but I'm not an expert. If for some reason it's correct practice for it to be as it is, we can close this ticket.

**Comment by kickapoo** [comment]
In my opinion it should not be a seperate component. We are using nuxtjs and a page basically is component of the vue-router.

That is needed is a Unit Test that mocks the endpoint and check the render process.

**Comment by aptiko** [comment]
We will not making Enhydris an SPA after all, so this issue is no longer valid.
