### ISSUE TITLE
API calls don't have the trailing slash

### ISSUE THREAD

**Issue by aptiko** [openmeteo/enhydris#178]
The frontend calls `/api/stations` instead of `/api/stations/`. This results in a redirect to `/api/stations/`. Except for the additional request, this is a problem because it causes some edge-case CORS issues on Firefox in development (this Firefox problem happens since fe490bc244a53b4d2a36b52bf410c9e9f1ec47f2).

How can we avoid this problem in the future? Should we perhaps set `APPEND_SLASH = False` in Django? In this case if the frontend developer forgets to append a slash, there will be no redirect, so the system won't work at all, so the developer will find the problem and fix it.

**Comment by kickapoo** [comment]
@aptiko my suggestion, for a unit test that "frontend developer forgets to append a slash" 

The structure I am suggesting :

```js
// file: api.js
export default {
  'stations': '/stations/'
}

// file: index.js (stations list)
import api from '.......api.js'
...
...  this.$axios.$post(`${api.stations}?page=${page}`);

// test.api.js 
import api from '.......api.js'
// for key in  api -> validate has first, last slashes 
```

**Comment by kickapoo** [comment]
## Backlog History
As discussed,  the backend solution `APPEND_SLASH = False` will be used

**Comment by aptiko** [comment]
We will not make Enhydris an SPA after all, so this issue is no longer valid.
