### ISSUE TITLE
Internal server error when attempting to use a nonexistent SRID

### ISSUE THREAD

**Issue by aptiko** [openmeteo/enhydris#18]
Create a new station or edit an existing station. Specify Abscissa and Ordinate, and a nonexistent SRID such as 210. Hit submit. Result:

`GetProj4StringSPI: Cannot find SRID (210) in spatial_ref_sys`

**Comment by kickapoo** [comment]
Searching around,  the error is related with database `PostGis SRID` in `PostgreSQL`.
My attempt for fix was to search for PostGis SRID list and write a validation but it seems it not available.

**Comment by aptiko** [comment]
You don't need to do that, just catch the exception.

**Comment by kickapoo** [comment]
I manage to catch the exception and  when user submit the form with invalid SRID gets the message `"Please enter a valid SRID code"`.
2 questions on that
1. Are you satisfied this the error message?
2. If there is an official link with the list of SRIDs? I thinking to update the message with that link for easy reference to users

**Comment by aptiko** [comment]
1. No, just use "Invalid SRID".
2. The official list of SRIDs is the database at http://www.epsg-registry.org/. However, there is no need to tell the user the link. If the user needs to specify a SRID, he knows what he's doing and the link will be useless (or confusing, because he might have been told "use SRID=2100" and he might not know what it means, but the link wouldn't explain it to him either). If the user doesn't know what he's doing, the link won't help him at all. So no link.

**Comment by kickapoo** [comment]
Need some help with the Unit Test. 

I am using a `try...except...` to catch `form.save` when user submits a invalid SRID. 
Even that 
```python 
except Exception:
     #https://docs.djangoproject.com/en/dev/ref/forms/api/#django.forms.Form.has_error
     form.add_error('srid', _("Invalid SRID"))
     return render_to_response('station_edit.html',  {'form': form}, context_instance=RequestContext(request))
```
returns the form in the context.

In the Unitest,
```python
response = self.client.post(reverse('station_add'), post_data, follow=True)
```
 there is no `response.context['form']`.

The test I am trying is:
```python
self.assertFormError(response, 'form', 'srid', 'Invalid SRID')
```

**Comment by aptiko** [comment]
First, you should catch all exceptions, but just this exception. It is `django.utils.db.InternalError`, but, again, you should catch all such InternalErrors. Do something like this:
```python
except InternalError as e:
    if 'Cannot find SRID' not in str(e):
        raise
    form.add_error('srid', _("Invalid SRID"))
    ...
```
In the unit test, I suggest to use `follow=False`. With a wrong SRID, you can test like this (untested):
```python
self.assertEqual(response.status, 200)
self.assertContains(response, 'Invalid SRID')
```
With a correct submission, the response code should be 302.

**Comment by kickapoo** [comment]
In order `self.assertContain` to return response.context , `follow=True` is needed (`response.status_code` should be 200) response.context is empty and for sure 'Invalid SRID' is not in there. 

I have tried everything I could possible understand and know but still I can't provide a UnitTest that simulates invalid `srid`.

I am starting to suspect that the django (>1.7)  `form.add_error` method is the reason. For instance, if I test  `response = self.client.post(reverse('station_add'), {})` (empty form), I am getting `response.context['form']` and `response.context[...]['field'].errors`.
