### ISSUE TITLE
Doesn't show copyright

### ISSUE THREAD

**Issue by aptiko** [openmeteo/enhydris#19]
Although the copyright of the data is registered in the database for each station, the station detail view doesn't display it at all.

(Also note that the openmeteo.org TOS is unclear with respect to people who only read the data.)

**Comment by kickapoo** [comment]
Look at : https://github.com/openmeteo/enhydris/blob/master/enhydris/hcore/views.py#L100
`display_copyright = settings.ENHYDRIS_DISPLAY_COPYRIGHT_INFO`

Also look at: https://github.com/openmeteo/enhydris/blob/master/enhydris/settings/base.py#L87 
`ENHYDRIS_DISPLAY_COPYRIGHT_INFO = False`

Changing `ENHYDRIS_DISPLAY_COPYRIGHT_INFO = True`,  copyrights are displayed.

**Comment by aptiko** [comment]
Thanks. So this issue is actually invalid. However, because the copyright notice shows terribly both in the master branch and in the bootstrap3 branch, I'm leaving the issue temporarily open until we fix it.

**Comment by kickapoo** [comment]
Probably is no good to comment to invalid issue, but how about like this: 
<img width="294" alt="screenshot 2015-09-01 21 28 02" src="https://cloud.githubusercontent.com/assets/5064612/9612870/aca5abac-50f0-11e5-938d-c70c5e1c2d9f.png">
<img width="345" alt="screenshot 2015-09-01 21 28 17" src="https://cloud.githubusercontent.com/assets/5064612/9612872/b03280b0-50f0-11e5-975d-9590c2514631.png">

**Comment by aptiko** [comment]
You are right: it's not good to start a discussion here. Let's follow procedure. I'm closing this issue and will open a new one.
