### ISSUE TITLE
Improve timeseries append/overwrite options

### ISSUE THREAD

**Issue by rozos** [openmeteo/enhydris#24]
Currently, when uploading timeseries two options are provided

1. Append
2. Overwrite

If the user selects 1, enhydris requires the uploaded timeseries starting date to be after the last date of the existing timeseries. If the user selects 2, enhydris requires the uploaded timeseries last date to be before the last date of the existing timeseries.

Recommended behavior

1. Append allows the user to insert values in the existing timeseries at anytime (before existing, in-between existing and after existing values), but it does not allow to overwrite existing values.
2. Overwrite does not restrict anything.

The graphic control should be a check box.

V.

**Comment by aptiko** [comment]
There's a myriad of little user interface improvements that Enhydris needs. This is just one of them. We will fix them little by little, and we will not track them. Therefore I'm marking this as (temporarily) wontfix.
