### ISSUE TITLE
type object 'Lookup' has no attribute 'objects'

### ISSUE THREAD

**Issue by aptiko** [openmeteo/enhydris#26]
Go to `/api` and click on `Lookup`. Internal server error: type object 'Lookup' has no attribute 'objects'

**Comment by aptiko** [comment]
Same problem with `/api/PoliticalDivisionManager` and `/api/StationManager`.

**Comment by kickapoo** [comment]
These is no `Lookup` or `/api/PoliticalDivisionManager` and `/api/StationManager`

The img below is the `api root`
<img width="884" alt="screenshot 2015-08-30 20 50 39" src="https://cloud.githubusercontent.com/assets/5064612/9568668/cc996528-4f58-11e5-8126-d8dd13265cc9.png">

**Comment by aptiko** [comment]
Strange. I certainly didn't imagine this problem. It probably disappeared when django-rest-framework was upgraded to version 3 or when Django was upgraded to 1.7 or 1.8.

**Comment by kickapoo** [comment]
Check this url: `/api/PoliticalDivision/1/`
`AssertionError at /api/PoliticalDivision/3/
'RetrieveAPIView' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.`

The same `error` occurs and to other urls (I haven't check yet one by one).

Maybe reopen with issue with different title?
