### ISSUE TITLE
Internal server error in some sort cases

### ISSUE THREAD

**Issue by aptiko** [openmeteo/enhydris#28]
http://openmeteo.org/?sort=999.9

```
ProgrammingError: syntax error at or near ".9"
LINE 1: ...ptr_id" = "hcore_gentity"."id" ) ORDER BY "999999".9 DESC LI...
```

**Comment by kickapoo** [comment]
This issue (along this #15 ) can be solve with my suggestion to use `http://datatables.net/` which by default supports: -Pagination, instant search and multi-column ordering. Also, various number of lines in `enhydris/hcore/views.py` that handle search will be deleted.

**Comment by kickapoo** [comment]
I tried several different url call to see this `?sort` argument handling. All tries are leading to different type of error (for example try `?sort=99`). 

So,  same as my previous comment, I will suggest to include a third party library provided by  `http://datatables.net/` in order to deal with all search (sort) relating problems.
It a well documented library, MIT licensed with many features that will upgrade `enhydris` UI to whole new level. It has only one  dependency, that is jQuery, which is already included in `enhydris` dependencies.

Finally, due to the fact that all our lists are enclosed to `table` html tags, datatables is an easy implementation, for example  with zero configuration:
```js
$(document).ready(function() {
    $('#example').DataTable();
} );
``` 
```html
<table id="example">
    ....
</table>
```
Probably we spend more time with deleting `search / sort` related backed code rather than to implement datatables library.

**Comment by aptiko** [comment]
`datatables` seem to be OK and popular. Unfortunately, it has practically only one contributor, who has, however, been consistently maintaining it for the last 5 years. If he stops maintaining it, we could be in trouble; not because we'll need to maintain it; we probably won't, given the popularity, but because the community may be slow to appoint a new leader (e.g. `django-registration` was also popular, but there were several years of confusion until a good alternative emerged). However, using it seems to be the best solution. Any alternative would require either many hours of work or substantially less functionality. It would be premature to say "I'm not certain it will be maintained, therefore I won't use it". Let's wait for that problem to arise before solving it.

Therefore, go with datatables.

**Comment by kickapoo** [comment]
Inside enhydris hcore codes (views tests etc) there are plenty of lines handling the previous search functionality.
As you pointed in the previous comment, about all future `datatables` maintenance problems might or not occur, I will suggest somehow to keep enhydris search functionality  code lines. For instance, we could create a branch keeping untouched this current version. 

My main concern is to have a back up `plug and play` option.

**Comment by kickapoo** [comment]
I am trying to implement the `datatables` and I have a question about previous sort functionality. 

There is a button in `station_list` page,  `List stations visible on map`. With `datatables`, this brakes, so the questions is: Do you want to keep this button? if yes, i will need to rewrite some javascript with the mapModule.

**Comment by aptiko** [comment]
Yes, I'm afraid the button is necessary. If the user zooms in some place in the map to find the area of interest, he will then want to limit stations viewed to those visible on the map.

**Comment by kickapoo** [comment]
We have a problem. I realised that if you create  a branch with the latest commits, 'List station visible on map' don't work. I thought a test existed for this.

I will suggest  an another similar approach that needs your review. I could implement a functionality that map will show only  search related items. For instance, if user search for 'Deukalion', map should show only 'Deukalion' stations.

**Comment by kickapoo** [comment]
First of all, to keep a clean track of the issue comment history, the previous suggestion of datatables.net will committed in separate commit after the 'List station visible on map' problem. 

Secondly, i would like an initial review to the suggested fix for this issue and if you could give some guideness for the Unit Test that must follow the patch.

**Comment by aptiko** [comment]
Essentially you did this:

```python
station_model_fields = set(Station._meta.get_all_field_names())
clean_sort_terms = set([item.replace('-','') for item in sort_order])
if not clean_sort_terms.issubset(station_model_fields):
    sort_order = list(clean_sort_terms.intersection(station_model_fields))
```

It's a good idea, but you can do it more simply like this:

```python
sort_order = [x for x in sort_order
              if x in Station._meta.get_all_field_names()]
```

Your solution, besides being more complicated, wouldn't work correctly because sets are unordered.

For the unit test, you can try `self.client.get(reverse(...) + '?sort=name&sort=999.9')` and then check the response. In order to avoid parsing the HTML of the response, you can check that Komboti comes before Tharbad by verifying that `response.content.index('Komboti')` is less than `response.content.index('Tharbad')`.

It might be a good idea if you also tried with '?sort=water_division&sort=name'; in that case, the order would be, I think, Komboti, Agios Athanasios, Tharbad.
