### ISSUE TITLE
Rewrite chart front-end code

### ISSUE THREAD

**Issue by aptiko** [openmeteo/enhydris#316]
The JS for the chart is in a mess and must be rewritten from scratch.

While we are currently using flot, we don't have a preference for it (neither are we against it). The person who decided to use flot and wrote the unreadable code isn't working with us any more. No-one in our team has any experience either with flot or with any other charting tool. Therefore, since the code is going to be rewritten anyway, we can use any charting tool. Proposals?

**Comment by yantakus** [comment]
I'd use highcharts: https://www.highcharts.com/demo

I worked with it before and it turned out to be good.

**Comment by aptiko** [comment]
Enhydris is free software (AGPLv3). AFAICS highcharts is non-free. Therefore it's a no-go.

**Comment by yantakus** [comment]
Yes, seems to be. I didn't even know because I worked with it in a commercial project. Will find an alternative.
