### ISSUE TITLE
Internal server error on /api/auth/login/

### ISSUE THREAD

**Issue by aptiko** [openmeteo/enhydris#342]
Attempting to visit `/api/auth/login/` on my development environment causes an internal server error. However production and staging seem to work fine.

**Comment by eyobofficial** [comment]
@aptiko So far, I am not able to replicate the bug on my machine. Visiting the `/api/auth/login/` URL is not creating any kind of server error for me - it is only bringing me the the browsable API page. Could you tell me the exact steps you followed when you face the bug? And when you say `on my development enviroment`, are you referering to the one that is created by the docker containers of the `openhi-docker-dev` repo or did you follow a different approach (e.g. using `virtualenv`)?

**Comment by aptiko** [comment]
I debugged it myself, since it was something that appeared only on my development environment (i.e. the one I had with docker). It turned out that the problem occurs when the Greek translation is activated, and somehow I had the `django-language: el` cookie set (on `localhost:8001`).

It's an error in a translation string in DRF; the translation string contains `"{method"}` instead of `"{method}"`, which causes DRF to crash.

I'm reassigning this to myself.
