### ISSUE TITLE
AssertionError: 'RetrieveAPIView' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method. 

### ISSUE THREAD

**Issue by aptiko** [openmeteo/enhydris#35]
Go here: http://openmeteo.org/api/WaterDivision/505/

Result:

AssertionError: 'RetrieveAPIView' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.

**Comment by kickapoo** [comment]
Please assign this one to me.
