### ISSUE TITLE
Implement new design for front page

### ISSUE THREAD

**Issue by aptiko** [openmeteo/enhydris#369]
Here is the new design for the front page:

![Front page, desktop](https://images.zenhubusercontent.com/5bb5c1e086a87b7bc2d840cf/beedba78-834d-4f41-bb12-97d128821d43)

![Front page, mobile](https://images.zenhubusercontent.com/5bb5c1e086a87b7bc2d840cf/38a83da8-67cc-40c7-9b73-59a1dc6882c2)

When the user has searched for stations, the design becomes like this:

![Search results page, desktop](https://images.zenhubusercontent.com/5bb5c1e086a87b7bc2d840cf/34012747-c0c1-4123-aa0d-87f4bcca9de9)

![Search results page, mobile](https://images.zenhubusercontent.com/5bb5c1e086a87b7bc2d840cf/f2b2a8a9-5ec0-45e8-abbe-91377e8931a0)

How can you know if this is the search results page or merely the front page? Well, the front page is `http://.../` whereas the search results page is `http://.../?q=...`, i.e. in the search results there's the `q` parameter. I believe that in the django template you can test for this by examining `request.GET.q`, like this:

    {% if request.GET.q %}
        ...
    {% endif %}

I haven't actually tested this, but you can try it. If it doesn't work we'll find a solution. This shouldn't stop you from proceeding.

The file from which you need to start is `enhydris/templates/enhydris/station_list/main-default.html`.

BTW, you don't need to change the map icons or the map pop-ups or otherwise the contents of the map, this issue is only about the rest. Also, the designer got a bit ahead here and added a language selector on the top right, which is future functionality. We don't have such a language selector yet, so just leave it out.

**Comment by ad0v0** [comment]
Hello! @aptiko 

Implemented new design for the front page and fixed code due to checklist. Please take a look when you get a chance.

Here's a pull request: https://github.com/openmeteo/enhydris/pull/393 

Many thanks!

**Comment by ad0v0** [comment]
@aptiko Hello! The feedback is implemented and ready for your review
