### ISSUE TITLE
Fix the look of the copyright notice

### ISSUE THREAD

**Issue by aptiko** [openmeteo/enhydris#39]
The copyright notice shows terribly.

**Comment by aptiko** [comment]
With respect to your proposals:
<img width="294" alt="screenshot 2015-09-01 21 28 02" src="https://cloud.githubusercontent.com/assets/5064612/9612870/aca5abac-50f0-11e5-938d-c70c5e1c2d9f.png">
<img width="345" alt="screenshot 2015-09-01 21 28 17" src="https://cloud.githubusercontent.com/assets/5064612/9612872/b03280b0-50f0-11e5-975d-9590c2514631.png">

1) Don't use "(c)", use "©".
2) Don't put a comma after the year, and don't change line.
3) It think we don't need the word "Copyright" since we have the copyright symbol.

So it should be like this:

© 2015 Decentralized Administration of Epirus and Western Macedonia

I also think it would be better to put it below the data, not below the map or chart; it looks like a legend and it might be confusing. But I am leaving this to you.

The other time we discussed about `<footer>`. I wonder whether a `<footer>` is an appropriate html element for such a thing. (Note that there can be many `<footer>`s in a page, I think there can be one in each section.)

**Comment by kickapoo** [comment]
Please check the update `bootstrap3` pull request. I have included in a bootstrap `well` class around copyrights div.

**Comment by aptiko** [comment]
Don't put a comma after the year, and don't put a full-stop at the end. Otherwise it's fine.
