### ISSUE TITLE
Use less space for "search stations" and "list stations visible on map"

### ISSUE THREAD

**Issue by aptiko** [openmeteo/enhydris#424]
Users complain that the search field and the "list stations visible on map" take too much space and they prevent them from viewing the stations. As a first step, I propose:

1) to remove the text from the "list stations visible on map" button (it should appear on hover though) and leave only a symbol, and put it on the right of the search help button (which appears with a question mark).
2) to remove the word "search" and instead use nothing? a right arrow? a magnifying glass? (in the latter case I guess we'll need to remove the magnifying glass on the left.)
3) to remove the search field width slightly.

If you think these changes are a good idea, please go ahead and make them. Otherwise, let's discuss about them.

FYI, in https://system.openhi.net/, I've added another search field on the bottom right (this is specific to the OpenHI project so I've put it in the customized theme for OpenHI; it's not in Enhydris).

**Comment by ad0v0** [comment]
> Users complain that the search field and the "list stations visible on map" take too much space and they prevent them from viewing the stations.

By the way, is this a mobile case issue, desktop or both?

**Comment by aptiko** [comment]
It's a desktop issue; I don't believe anyone uses the site on mobile at the moment.

**Comment by ad0v0** [comment]
Desktop, original look: https://prnt.sc/zulg5f, 
and the new look:
- static https://prnt.sc/zvfzpo
- with hover effect https://prnt.sc/zvh9gg

**Comment by ad0v0** [comment]
> FYI, in https://system.openhi.net/, I've added another search field on the bottom right (this is specific to the OpenHI project so I've put it in the customized theme for OpenHI; it's not in Enhydris).

Thanks for the info! Are there any actions that are required from my side?

**Comment by aptiko** [comment]
I like the new look. Some notes:
1. I think that the search tips (the button with the question mark) is shorter than the search field and the list-stations-visible-on-map button. To me this looks a little odd.
2. Does the list-stations-visible-on-map change size when you hover? I think this would be confusing. I think it would be better for a tooltip to popup instead.

And, yes, no actions are required from your side regarding the other search box.

**Comment by ad0v0** [comment]
Thanks for the notes!

1) I would disagree with you, as currently it creates a size contrast and makes easier to differ buttons from one another. But if you think that it would be better if I adjust sizing, then I'll definetely listen to your opinion and do that. This is how it would look then: https://prnt.sc/10003s5
2) Yes, I thought about the same solution with a tooltip as an alternative, but at the same time thought that what you've meant here:
> to remove the text from the "list stations visible on map" button (it should appear on hover though) 

was to leave the existing button . This a how it would look: https://stackoverflow.com/questions/33888214/css-animation-to-extend-button-text-on-hover. But I've got your point with the confusion and I'm going to create a tooltip instead

**Comment by ad0v0** [comment]
What happened to the scrollbar in the block with search results https://prnt.sc/1000ph7? Should I fix it or leave it as is?

**Comment by ad0v0** [comment]
@aptiko Ready for your review!
