### ISSUE TITLE
Very slow first page if there are many stations

### ISSUE THREAD

**Issue by aptiko** [openmeteo/enhydris#70]
The front page of main.hydroscope.gr is very slow. It needs either caching, or pagination, or both.

**Comment by kickapoo** [comment]
For this I could apply a basic  Django Pagination to table results.
1. https://docs.djangoproject.com/en/1.11/topics/pagination/
2. View to alter: https://github.com/openmeteo/enhydris/blob/master/enhydris/hcore/views.py#L447

Another solution and I think you will not like is to "wrap" this table results in as https://datatables.net/ table.
Pros are:
1. Search on the top of the table
2. Pagination in browser site (not other change)
3. Very simple to test it even its a matter of 10 minutes in your local setup
Con are:
1. New external lib
2. You dont like the (1)

**Comment by MounirMesselmeni** [comment]
- Use django-debug-toolbar in your dev env to identify duplicated queries and what's going wrong.
- In `StationListBaseView.get_queryset` method, Add a `return result.prefetech_related('water_basin', 'water_division', 'political_division', 'owner', 'stype')`
You are basically running 5 additional sql queries for each station, so if you have 1000 stations, this will results in more than 5000 sql queries.
This can improve a lot the performance of that page.

**Comment by aptiko** [comment]
Thank you for this comments @MounirMesselmeni. I hadn't noticed. This would probably make it a lot faster. Unfortunately it wouldn't solve the general problem, I believe, which is that pagination is needed. So I have added pagination but I will keep these things in mind.
