### ISSUE TITLE
Greek search is affected by accents

### ISSUE THREAD

**Issue by aptiko** [openmeteo/enhydris#71]
Go to http://kyy.hydroscope.gr/ and search for "βασίλειος"; it returns no results. But if you search for "βασιλειος", without an accent, it does return three results.

**Comment by MounirMesselmeni** [comment]
This may help you: https://docs.djangoproject.com/en/2.0/ref/contrib/postgres/lookups/#unaccent

**Comment by kickapoo** [comment]
@aptiko Please assign if it make sense to you to update all `__icontains`  in Station List search Query set like: 
```python
     Q(name__icontains=search_term) 
```

to `__unaccent__icontains`

```python
    Author.objects.filter(name__unaccent__icontains='Helen') 
    #[<Author: Helen Mirren>, <Author: Helena Bonham Carter>, <Author: Hélène Joy>]
```
reference: https://docs.djangoproject.com/en/1.11/topics/db/search/#a-database-s-more-advanced-comparison-functions

**Comment by kickapoo** [comment]
Trying to implement this by changing a single field

```
# views.py | line 304
Q(name__unaccent__icontains=search_term)
```
test fails due.
```
django.core.exceptions.FieldError: Unsupported lookup 'unaccent' for CharField or join on the field not permitted.
```

**Comment by MounirMesselmeni** [comment]
@kickapoo Unaccent is postgresql specific, it will not work with spatialite. I thought you were using postgis. You have to find sqlite specific solution for that.

**Comment by aptiko** [comment]
PostgreSQL-specific is fine, but please keep SQLite compatibility and PostgreSQL-without-unaccent compatibility (i.e. use unaccent if available, don't use it if unavailable, skip the unaccent unit tests if unaccent is unavailable).

Don't add Greek letter support; this is installation-specific.
