### ISSUE TITLE
User does not have permissions to edit a station

### ISSUE THREAD

**Issue by aptiko** [openmeteo/enhydris#73]
In kyy.hydroscope.gr, we have a user who belongs to the "editors" group (but is not a superuser), but they don't have an "edit" button in stations and timeseries.

**Comment by kickapoo** [comment]
Have you check the editor that permission add change station in the group?
https://github.com/openmeteo/enhydris/blob/master/enhydris/hcore/views.py#L930

**Comment by aptiko** [comment]
The permissions system has had a huge overhaul. This bug is extremely unlikely to still exist. Closing.
