### ISSUE TITLE
Internal server error when accessing nonexistent timeseries

### ISSUE THREAD

**Issue by aptiko** [openmeteo/enhydris#76]
(http://main.hydroscope.gr/timeseries/data/) (?object_id=11)

In views.py, line 643: DoesNotExist

**Comment by kickapoo** [comment]
There is the following test:
(test_urls.py) : https://github.com/openmeteo/enhydris/blob/master/enhydris/hcore/tests/test_urls.py
with the comment 
```
    #TODO: Run this for all applications, somehow
    #TODO: More customization: 404s, etc
    #TODO: Make this run automatic for all
```
I was thinking to update this test for this issue with the following pseudo code:

```python
# Get all the names of urlpatterns 
enhydris_urlpatters_names = [ 'login', 'logout', 'timeseries' etc]

# Create a dict that hold the test information with structure, ex login
# Guest: User with no authentication , 
# User: User that can authenticate, 
# SuperUser: User that can authenticate with admin rights

testing_urlpatterns = [
{
  'login': {
      'guest': 
               {
                  'method': 'post', 
                  'follow': True # redirect
                  'status_code': 404, 
                   data: { 'username': 'kickapoo', 'password': '123' } # invalid ,
              },
      'user': 
               {
                  'method': 'post', 
                  'follow': True # redirect
                  'status_code': 200, 
                   data: { 'username': 'aptiko', 'password': '1234' } # valid ,
              },
       etc
}
]

# Test 1: 
# For key in testing_urlpatterns.keys() if not in  enhydris_urlpatters_names --> fail 
# --> There is not test for a urlpattern name, need an update of testing_urlpatterns list object.

# Test 2:
# For key in testing_urlpatterns.keys() 
# -->  c = Client() 
# --> and based on method, follow make c.post or c.get.
# --> assert based on status_code
```

I dont know if I am overthinking this or I am in wrong direction due my minor experience in TDD approach.

For this the issue a more simple test can be used but I was thinking to make a more general use Unit Test. 

Notify: @aptiko

**Comment by aptiko** [comment]
I don't know the reasoning and logic behind the `SmokeTestCase`. I haven't written that test. I also don't know what a "smoke test" is (though the term exists), neither if the term is properly being used here. So until we have some clear understanding of what is going on here, I'd say leave this test alone. Besides, `test_urls.py` is supposed to test stuff that is in `urls.py`, whereas our problem is in `views.py`. So our test should go to `test_views.py`.

Although the current test structure of Enhydris is not ideal, I suggest to add this test in `TsTestCase`, immediately after `test_get_empty_timeseries_data_for_chart()`, which tests something similar.
