### ISSUE TITLE
TypeError: Transform only accepts CoordTransform, SpatialReference, string, and integer objects

### ISSUE THREAD

**Issue by aptiko** [openmeteo/enhydris#79]
cfe6044 fixed the CSV view for most cases, but appending "?format=csv" to the url produces an error when in the list of stations there is a station that has a point assigned but in which srid is null. Such a case should not exist (it may be an error elsewhere), but it does exist, so we must handle this (assuming a default srid=4326).

**Comment by kickapoo** [comment]
`srid` against the model is tested in ` test_original_coordinates_with_null_srid`:
https://github.com/openmeteo/enhydris/blob/master/enhydris/hcore/tests/test_models.py#L123
in which basically tests that `srid` can accept null as value.
