### ISSUE TITLE
Update installation instructions (and release notes) for the front-end

### ISSUE THREAD

**Issue by aptiko** [openmeteo/enhydris#92]
Requires #88.
Child of aptiko/openhi#17.

**Comment by kickapoo** [comment]
.env.sample is the sample for .env to be configured.

- Tittle: Nothting needs to remove and in Import Page Title issue is replaced
- NPM_CONFIG_PRODUCTION:  deployment  
- HOST: deployment
- NODE_ENV: deployment
 Example usage: https://nuxtjs.org/faq/heroku-deployment/
