### ISSUE TITLE
Remove code for dealing with null co-ordinates

### ISSUE THREAD

**Issue by aptiko** [openmeteo/enhydris#98]
Child of aptiko/openhi#18.

After fixing #93, there's some code in the frontend that isn't needed any more.

**Comment by kickapoo** [comment]
http://stage.openmeteo.org/api/stations/

still holds null points.

**Comment by aptiko** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a user, I want to see entities on the map so that I can find the data I want (3.1.3b, 6.2)](https://trello.com/c/zMkluAZT/1-as-a-user-i-want-to-see-entities-on-the-map-so-that-i-can-find-the-data-i-want-313b-62)
